### DISCUSSION TITLE
Unable to list (runway) orders

### DISCUSSION THREAD

**Discussion by de-raaf-media** [duncanmcclean/simple-commerce#1041] [Help] [answered]
Not sure if this is a configuration issue or something else. I get an error when I click on Orders (/cp/runway/orders).

`Call to a member function display()` on null in `/vendor/statamic-rad-pack/runway/resources/views/index.blade.php`

I tried to debug this. 

In `vendor/statamic-rad-pack/runway/src/Query/Scopes/Filters/Fields/Models.php` on Line 22 this seems to generate the error:

`$resource->titleField() => $resource->blueprint()->field($resource->titleField())->display(),`

The value of `$resource->blueprint()->field($resource->titleField())` is "Orders"

So it seems the display() function is causing the error in order overview in CP.

I am using database orders and I am using eloquent users. The eloquent users are visible on the customers page on /cp/users. I have no clue why this error occurs.

**Comment by duncanmcclean** [comment, marked as answer]
Can you provide the contents of the blueprint's YAML file?

**Comment by de-raaf-media** [comment]
This pointed me in the right direction I guess ;-) The error is gone. Thanks!

Title and customer are empty but that's another issue I have not looked into yet.

**Comment by de-raaf-media** [comment]
Seems I have one last issue (hopefully) after the upgrade from 5 to 6. The user is no longer connected to the order in the CP. There is however an order in the database and it does have a customer_id that is the correct id.

**Reply by duncanmcclean** [reply]
You might need to swap the Customer field in the order blueprint to be a User field instead of a Runway BelongsTo field.

**Comment by de-raaf-media** [comment]
Yeah did that already. I am using an eloquent user. And in my orders.yaml i use it like follows:

```
 - handle: customer
        field:
          max_items: 1
          mode: select
          type: users
          display: Customer
          listable: hidden
          instructions_position: above
          visibility: visible
          replicator_preview: true
          hide_display: false
```

Or is it mandatory to user CustomerModel.php? I did not modify that but maybe I should use it? My simple-commerce.php uses the UserCustomerRepository.

```
'customers' => [
        'repository' => \DuncanMcClean\SimpleCommerce\Customers\UserCustomerRepository::class,
        'collection' => 'customers'
],

'orders' => [
        'repository' => \DuncanMcClean\SimpleCommerce\Orders\EloquentOrderRepository::class,
        'model' => \DuncanMcClean\SimpleCommerce\Orders\OrderModel::class,
],
```
