### DISCUSSION TITLE
Order Date in default blueprint/setup

### DISCUSSION THREAD

**Discussion by Web10-Joris** [duncanmcclean/simple-commerce#1046] [Feature Requests]
Is it possible to include the order dates in the default setup? I already found this discussion #947 , but I think it would be helpful for everyone to have this field available in the blueprint by default, on both file-based & database orders. This way the order listing table can also be sorted on the order date, to see the most recent orders first. (This can also be sorted on order number if incrementing ofcourse, but I feel like date is more natural/stable in that case).

**Comment by duncanmcclean** [comment]
Both flat-file & database orders should already have an "Order Date" field in their blueprints. 

If you don't have one, add this field to your order blueprint:

```yaml
          - handle: order_date
            field:
              mode: single
              inline: false
              full_width: false
              columns: 1
              rows: 1
              time_enabled: false
              time_seconds_enabled: false
              type: date
              display: 'Order Date'
              icon: date
              listable: true
              instructions_position: above
              visibility: read_only
              replicator_preview: true
              hide_display: false
```

However, I've just realised there's a bug with it not returning any value when using database orders which I've just fixed in #1053 and will tag a release for shortly.
