### DISCUSSION TITLE
Complex Products

### DISCUSSION THREAD

**Discussion by sbrow** [duncanmcclean/simple-commerce#1064] [Help]
## Background

Hello! I apologize, as I suspect you will be sick and tired of me soon if you aren't already :sweat_smile: 

I am migrating my Company's website from WordPress+WooCommerce to Statamic+SimpleCommerce. We effectively have two products at this point, but we have a great number of prices based on the quantity purchased.

Because of the way that WooCommerce is structured, we had to make a separate "product" for most of our prices, except for the few we were able to implement using product variations. We also have a number of items we need to track the stock of, though they aren't technically products. i.e. shipping boxes and company logo stickers included with every order. I've included a breakdown of our product lineup for context.

I like the way that Stripe breaks things down into prices and products, but we want to keep our subscription models in-house in case we want to pivot to another payment provider.

<details>
<summary>Product Breakdown</summary>

```yaml
products:
  - product-x:
      prices:
      -  1 unit   @ $  59.99
      -  2 units @ $ 116.00
      -  4 units @ $ 228.00
      -  6 units @ $ 228.00 (wholesaler only)
      - 24 units @ $ 840.00 (wholesaler only)
      -  1 unit  @ $  99.95 / month
      -  2 units @ $ 192.00 / month
      -  1 unit  @ $  84.00 / month for 12 months + $24.00 Up-front
      -  2 units @ $ 160.00 / month for 12 months + $48.00 Up-front
  - product-y:
      prices:
      - $  28.00 /  2 units
      - $ 180.00 / 15 units (wholesaler only)
bundles:
  - starter-bundle:
      products:
        product-x: 1
        product-y: 1
stocked:
- product-x
- product-y
- Company Logo Stickers
- Product X Info Pamphlet
- 2 Unit Shipping container
- 4 Unit Shipping container
- 6 Unit Shipping container
```

</details>

## What I'm Looking for (TL; DR)

I appreciate that Simple Commerce is _Simple_ Commerce. I realize that all of this is far too complex to integrate into the main SC repo. What I'd like to know is

1. **What's the best way to integrate a complex pricing structure** into another addon, that will play nice with future versions of SC.
2. Can stock be tracked on collections other than products?

Thank you for your time!
