### ISSUE TITLE
Use Eloquent User Model instead of Customer model

### ISSUE THREAD

**Issue by zedix** [duncanmcclean/simple-commerce#198]
## Description

> Users are the member accounts to your site or application.

```php
    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],
    ]
```
I'm currently using the `eloquent` driver to handle my statamic users (I would like to keep a single table to handle admin users and customers).

It allows make use of the built-in Users view in Control Panel.
It allows to make use of `{{ user:register_form }}` `{{ user:login_form }}` tags as well.

Would be nice if we could opt-out from the default `Customer` model to use the model configured in config `auth.php`.

Ideally, I would also like to retrieve the custom fields defined in the user blueprint, in the checkout form.

In example, I may have replaced the default `name` field by `first_name` and `last_name`.

```yaml
fields:
  -
    handle: first_name
    field:
      type: text
      display: First Name
  -
    handle: last_name
    field:
      type: text
      display: Last Name
  -
    handle: email
    field:
      type: text
      input: email
      display: Email Address
...
```

In that situation, the simple-commerce checkout form should display and handle the right fields.
