### ISSUE TITLE
Getting error when hitting checkout/payment from checkout/address

### ISSUE THREAD

**Issue by twd3** [duncanmcclean/simple-commerce#307]
I edited the checkout process a bit. Got rid of account and shipping. In my setup they go:
login>add to cart>cart>checkout/email>checkout/address>checkout/payment

When I hit payment I'm getting:
**Argument 1 passed to DoubleThreeDigital\SimpleCommerce\Repositories\CustomerRepository::findByEmail() must be of the type string, null given, called in C:\_statamic\site\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php on line 261** 

I checked to see if there is a customer entry for this test user and there is. The file is named: test-at-testnet.md I assume that is right. I was going to get rid of the checkout/email step too because they're logged in but I think the cart needs it?

I'm a bit worried about this one though because I've seen the payment step work in this setup. I'm just using the default checkout.

...

I expected to see the stripe payment with a cart to the right.

...

## Environment

Statamic 3.0.13 Pro
Laravel 7.26.1
PHP 7.4.6
doublethreedigital/simple-commerce 2.0.17
optimoapps/statamic-bard-text-align 1.0.0
spatie/statamic-responsive-images 1.2.3

**Comment by duncanmcclean** [comment]
A few questions:

* Is there a `customer` set on the order entry, you should be able to see it in the file. It should have the ID of the customer entry.

* Can you share the full stack trace so I can see where it is that's calling the `CustomerRepository`?

**Comment by twd3** [comment]
Okay, no, after I hit the email step it adds the email to the order but then I hit address and it doesn't add anything to the order, then I hit payment and get this error.

Here is what the order .md files ends up looking like:
```
---
title: '#2001'
items:
  -
    id: 87e0072a-410c-4c5f-929a-3a958a40d022
    product: 96a4e71d-6384-495a-93d3-815cd904350e
    quantity: 1
    total: 100500
is_paid: false
grand_total: 100701
items_total: 100500
tax_total: 201
shipping_total: 0
coupon_total: 0
order_status: cart
email: test@test.net
id: de3c35fb-a731-413d-ba00-be50f1577229
published: false
---
```
Here is that customer (customer is also a user):
```
---
email: test@test.net
id: 03f192e7-8df7-4f25-a8c0-046d672c87c9
published: false
---
```
