### ISSUE TITLE
Update cart with Ajax throws exception

### ISSUE THREAD

**Issue by JanJanssensDigiti** [duncanmcclean/simple-commerce#349]
A couple days ago I was trying to use Ajax for updating the cart but stumbled upon a issue simular to #348. Didn't had the time yet to report it but I thought to first try out your changes in 2.2.4 & 2.2.5. Today I was testing it again with the newest release of simple commerce but now throws following exception. Not sure why it can't find the product entry.

```
{
    "message": "Order could not be found: f9522303-a452-4341-b087-a5632540ca60",
    "exception": "DoubleThreeDigital\\SimpleCommerce\\Exceptions\\OrderNotFound",
    "file": "/Users/janjanssens/Documents/Sites/Valet/sc-starter-kit/vendor/doublethreedigital/simple-commerce/src/Support/Traits/IsEntry.php",
    "line": 32,
    "trace": [
        {
            "file": "/Users/janjanssens/Documents/Sites/Valet/sc-starter-kit/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php",
            "line": 261,
            "function": "find",
            "class": "DoubleThreeDigital\\SimpleCommerce\\Products\\Product",
            "type": "->"
        },
    ...
```

## How to reproduce

1. Use the ajax example provided in the documentation.
2. add product in your cart
3. Go to cart and change the quantity of a product in your cart

I used the below code
```
$(".ajax-update").change(function(){ 
  let params = {
    '_token': $(this).find('input[name="_token"]').val(),
    'product': $(this).attr('item'),
    'quantity': $(this).find('input[name="quantity"]').val()
  }
  
  let action = $(this).attr('action');
  console.log(action);
  axios.post(action, params)
  .then((response) => {
  	console.alert(message)
  })
});
```

## What I expected

To update the cart and give a JSON response back.

## Environment

Statamic 3.0.42 Pro
Laravel 8.27.0
PHP 7.4.13
doublethreedigital/simple-commerce 2.2.5

**Comment by duncanmcclean** [comment]
Just to double check, does an entry defiantly exist in your order collection with that ID?

**Comment by JanJanssensDigiti** [comment]
Hopes this clarifies it a bit. The id in the exception is the cart item id of the product that it wants to update.

```
{
    "message": "Order could not be found: 9cc0f3f8-d6bb-444a-a0d2-e7569c235a66",
    "exception": "DoubleThreeDigital\\SimpleCommerce\\Exceptions\\OrderNotFound",
    "file": "/Users/janjanssens/Documents/Sites/Valet/sc-starter-kit/vendor/doublethreedigital/simple-commerce/src/Support/Traits/IsEntry.php",
    "line": 32,
    "trace": [
        {
            "file": "/Users/janjanssens/Documents/Sites/Valet/sc-starter-kit/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php",
            "line": 261,
            "function": "find",
            "class": "DoubleThreeDigital\\SimpleCommerce\\Products\\Product",
            "type": "->"
        },
        {
            "file": "/Users/janjanssens/Documents/Sites/Valet/sc-starter-kit/vendor/doublethreedigital/simple-commerce/src/Orders/Calculator.php",
            "line": 29,
            "function": "__callStatic",
            "class": "Illuminate\\Support\\Facades\\Facade",
            "type": "::"
        },
```

Order id : f85a4471-1723-4c78-80c7-5353fd8cb3d4
Cart item id: 9cc0f3f8-d6bb-444a-a0d2-e7569c235a66
Product id: 2fa3a527-87f7-4c2e-8388-f550852fbc3a

**Comment by duncanmcclean** [comment]
That's strange that it would be trying to find an Order with the cart item ID. What does the YAML file of your order look like?

**Comment by JanJanssensDigiti** [comment]
```
---
title: '#2017'
is_paid: false
grand_total: 1000
items_total: 826
tax_total: 174
shipping_total: 0
coupon_total: 0
order_status: cart
items:
  -
    id: 9cc0f3f8-d6bb-444a-a0d2-e7569c235a66
    product: 9cc0f3f8-d6bb-444a-a0d2-e7569c235a66
    quantity: '2'
    total: 826
    variant:
      variant: Rood
      product: 2fa3a527-87f7-4c2e-8388-f550852fbc3a
id: f85a4471-1723-4c78-80c7-5353fd8cb3d4
published: false
---
```

I think it is trying to find a product with the cart item id instead of the product id. The exception itself is just a bit misleading because the find function in the IsEntry trait throws an OrderNotFound exception if no entry is found.
