### ISSUE TITLE
Issue with upgrade  2.2.21 -> 2.3

### ISSUE THREAD

**Issue by studiovlijmscherp** [duncanmcclean/simple-commerce#446]
### What's the issue you're running into?

We're using the 'default' checkout routes:
```
Route::redirect('/checkout', '/checkout/information');
Route::statamic('/checkout/information', 'checkout.information', ['title' => 'Checkout - Information']);
Route::statamic('/checkout/shipping', 'checkout.shipping', ['title' => 'Checkout - Shipping']);
Route::statamic('/checkout/payment', 'checkout.payment', ['title' => 'Checkout - Payment']);
Route::statamic('/checkout/complete', 'checkout.complete', ['title' => 'Bestelling afgerond']);
```

After  the upgrade from 2.2.21 -> 2.3 we get a validation error for two missing fields when going from 
/checkout/information to
/checkout/shipping

'Order date' and  'Delivery  date' are missing. Not sure why  this happens.
We set the 'Delivery  date' @/checkout/shipping. 'Order date' should be set automatic I think?

### Steps to reproduce

- Upgrade from 2.2.21 -> 2.3
- Checkout using mentioned routes

### Environment

Before upgrade:

Statamic 3.1.9 Solo
Laravel 8.35.1
PHP 7.4.13
cnj/seotamic 2.0.3
doublethreedigital/duplicator 1.3.1
doublethreedigital/simple-commerce 2.2.21
pecotamic/sitemap 1.2.1

**Comment by duncanmcclean** [comment]
Can you share what your order blueprint looks like (`resources/blueprints/collections/orders/orders.yaml`)?

**Comment by studiovlijmscherp** [comment]
```
title: Order
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: items
        field:
          fields:
            -
              handle: id
              field:
                type: hidden
                localizable: false
                listable: hidden
                display: ID
            -
              handle: product
              field:
                max_items: 1
                mode: default
                collections:
                  - products
                type: entries
                localizable: false
                listable: hidden
                display: Product
                validate: required
            -
              handle: variant
              field:
                display: Variant
                type: product_variant
                icon: product_variant
                width: 50
                listable: hidden
            -
              handle: quantity
              field:
                input_type: number
                type: text
                localizable: false
                listable: hidden
                display: Quantity
            -
              handle: total
              field:
                read_only: false
                type: money
                localizable: false
                listable: hidden
                display: Total
                validate: required
          mode: stacked
          reorderable: true
          type: grid
          listable: hidden
          display: Items
      -
        handle: totals
        field:
          type: section
          listable: hidden
          display: Totals
      -
        handle: grand_total
        field:
          type: money
          display: 'Grand Total'
          read_only: true
          validate: required
          width: 33
          listable: hidden
      -
        handle: items_total
        field:
          type: money
          display: 'Items Total'
          read_only: true
          validate: required
          width: 33
          listable: hidden
      -
        handle: shipping_total
        field:
          type: money
          display: 'Shipping Total'
          read_only: true
          validate: required
          width: 33
          listable: hidden
      -
        handle: tax_total
        field:
          type: money
          display: 'Tax Total'
          read_only: true
          validate: required
          width: 33
          listable: hidden
      -
        handle: coupon_total
        field:
          type: money
          display: 'Coupon Total'
          read_only: true
          validate: required
          width: 33
          listable: hidden
  addresses:
    display: Addresses
    fields:
      -
        handle: shipping_section
        field:
          type: section
          listable: hidden
          display: Shipping
      -
        handle: shipping_name
        field:
          input_type: text
          type: text
          listable: hidden
          display: 'Shipping Name'
      -
        handle: shipping_address
        field:
          input_type: text
          type: text
          listable: hidden
          display: 'Shipping Address'
      -
        handle: shipping_city
        field:
          input_type: text
          type: text
          listable: hidden
          display: 'Shipping City'
      -
        handle: shipping_country
        field:
          input_type: text
          type: text
          width: 50
          listable: hidden
          display: 'Shipping Country'
      -
        handle: shipping_zip_code
        field:
          input_type: text
          type: text
          width: 50
          listable: hidden
          display: 'Shipping Postal Code'
      -
        handle: shipping_phone
        field:
          input_type: tel
          antlers: false
          display: Telefoonnummer
          type: text
          icon: text
          listable: hidden
          validate:
            - required
      -
        handle: billing_section
        field:
          type: section
          listable: hidden
          display: Billing
      -
        handle: use_shipping_address_for_billing
        field:
          type: toggle
          listable: hidden
          display: 'Use shipping address for billing?'
      -
        handle: billing_name
        field:
          input_type: text
          type: text
          listable: hidden
          display: 'Billing Name'
          unless:
            use_shipping_address_for_billing: 'equals true'
      -
        handle: billing_address
        field:
          input_type: text
          type: text
          listable: hidden
          display: 'Billing Address'
          unless:
            use_shipping_address_for_billing: 'equals true'
      -
        handle: billing_city
        field:
          input_type: text
          type: text
          listable: hidden
          display: 'Billing City'
          unless:
            use_shipping_address_for_billing: 'equals true'
      -
        handle: billing_country
        field:
          input_type: text
          type: text
          width: 50
          listable: hidden
          display: 'Billing Country'
          unless:
            use_shipping_address_for_billing: 'equals true'
      -
        handle: billing_zip_code
        field:
          input_type: text
          type: text
          width: 50
          listable: hidden
          display: 'Billing Postal Code'
          unless:
            use_shipping_address_for_billing: 'equals true'
  sidebar:
    display: Sidebar
    fields:
      -
        handle: customer
        field:
          max_items: 1
          mode: default
          collections:
            - customers
          type: entries
          listable: hidden
          display: Customer
      -
        handle: coupon
        field:
          max_items: 1
          mode: select
          collections:
            - coupons
          type: entries
          listable: hidden
          display: Coupon
      -
        handle: order_date
        field:
          mode: single
          time_enabled: true
          time_required: true
          earliest_date: '1900-01-01'
          full_width: false
          inline: false
          columns: 1
          rows: 1
          type: date
          listable: hidden
          display: 'Order Date'
          validate: required
      -
        handle: order_status
        field:
          max_items: 1
          mode: default
          taxonomies:
            - order_statuses
          type: terms
          listable: hidden
          display: 'Order Status'
          default: cart
      -
        handle: is_paid
        field:
          type: toggle
          listable: hidden
          display: 'Is Paid?'
      -
        handle: delivery_date
        field:
          mode: single
          time_enabled: false
          time_required: false
          earliest_date: '2021-01-01'
          full_width: false
          inline: false
          columns: 1
          rows: 1
          display: Leverdatum
          type: date
          icon: date
          listable: hidden
          validate:
            - required
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
```
