### ISSUE TITLE
Error when processign order with product variant(s)

### ISSUE THREAD

**Issue by wautersj** [duncanmcclean/simple-commerce#939]
### Description

I'm redirected to the failed route if i try to process an order with a product variant in it.
When processing an order with no variant, after processing will be redirected to the completed route.

(Also; in both cases, not receiving emails anymore)

### Steps to reproduce

Add product with variant to cart
Fill in checkout information
Continue to payment
Get redirected

```
[2023-11-25 15:35:30] laravel.ERROR: DoubleThreeDigital\SimpleCommerce\Products\Product::variant(): Argument #1 ($optionKey) must be of type string, array given, called in /data/sites/web/digiti-commerce-demobe/releases/11/vendor/doublethreedigital/sc-digital-products/src/Listeners/ProcessCheckout.php on line 26 {"exception":"[object] (TypeError(code: 0): DoubleThreeDigital\\SimpleCommerce\\Products\\Product::variant(): Argument #1 ($optionKey) must be of type string, array given, called in /data/sites/web/digiti-commerce-demobe/releases/11/vendor/doublethreedigital/sc-digital-products/src/Listeners/ProcessCheckout.php on line 26 at /data/sites/web/digiti-commerce-demobe/releases/11/vendor/doublethreedigital/simple-commerce/src/Products/Product.php:150)
[stacktrace]
#0 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/doublethreedigital/sc-digital-products/src/Listeners/ProcessCheckout.php(26): DoubleThreeDigital\\SimpleCommerce\\Products\\Product->variant(Array)
#1 [internal function]: DoubleThreeDigital\\DigitalProducts\\Listeners\\ProcessCheckout->DoubleThreeDigital\\DigitalProducts\\Listeners\\{closure}(Object(DoubleThreeDigital\\SimpleCommerce\\Orders\\LineItem), 0)
#2 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(871): array_filter(Array, Object(Closure), 1)
#3 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(387): Illuminate\\Support\\Arr::where(Array, Object(Closure))
#4 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/doublethreedigital/sc-digital-products/src/Listeners/ProcessCheckout.php(22): Illuminate\\Support\\Collection->filter(Object(Closure))
#5 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(478): DoubleThreeDigital\\DigitalProducts\\Listeners\\ProcessCheckout->handle(Object(DoubleThreeDigital\\SimpleCommerce\\Events\\OrderStatusUpdated))
#6 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(286): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('...', Array)
#7 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(266): Illuminate\\Events\\Dispatcher->invokeListeners('...', Array, false)
#8 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(433): Illuminate\\Events\\Dispatcher->dispatch('...')
#9 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/doublethreedigital/simple-commerce/src/Orders/Order.php(306): event(Object(DoubleThreeDigital\\SimpleCommerce\\Events\\OrderStatusUpdated))
#10 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/doublethreedigital/simple-commerce/src/Gateways/BaseGateway.php(143): DoubleThreeDigital\\SimpleCommerce\\Orders\\Order->updateOrderStatus(Object(DoubleThreeDigital\\SimpleCommerce\\Orders\\OrderStatus))
#11 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/doublethreedigital/simple-commerce/src/Gateways/Builtin/MollieGateway.php(99): DoubleThreeDigital\\SimpleCommerce\\Gateways\\BaseGateway->markOrderAsPaid(Object(DoubleThreeDigital\\SimpleCommerce\\Orders\\Order))
#12 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/doublethreedigital/simple-commerce/src/Gateways/Manager.php(104): DoubleThreeDigital\\SimpleCommerce\\Gateways\\Builtin\\MollieGateway->webhook(Object(Illuminate\\Http\\Request))
#13 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/doublethreedigital/simple-commerce/src/Http/Controllers/GatewayWebhookController.php(27): DoubleThreeDigital\\SimpleCommerce\\Gateways\\Manager->webhook(Object(Illuminate\\Http\\Request))
#14 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): DoubleThreeDigital\\SimpleCommerce\\Http\\Controllers\\GatewayWebhookController->index(Object(Illuminate\\Http\\Request), Array)
#15 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction('...', Array)
#16 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(DoubleThreeDigital\\SimpleCommerce\\Http\\Controllers\\GatewayWebhookController), '...')
#17 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#18 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Routing\\Route->run()
#19 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#26 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#33 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#34 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#35 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#36 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#37 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#38 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/statamic/cms/src/Http/Middleware/StopImpersonating.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\StopImpersonating->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/livewire/livewire/src/Features/SupportDisablingBackButtonCache/DisableBackButtonCacheMiddleware.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\Features\\SupportDisablingBackButtonCache\\DisableBackButtonCacheMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#68 /data/sites/web/digiti-commerce-demobe/releases/11/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#69 /data/sites/web/digiti-commerce-demobe/releases/11/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#70 {main}

```

### Environment

Environment
Application Name: Slagerij Kurt
Laravel Version: 10.33.0
PHP Version: 8.2.13
Composer Version: 2.6.5
Environment: local
Debug Mode: OFF
URL: shop-demo.digiti.be
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: apc
Database: mysql
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Currencies: EUR, EUR
Gateways: Mollie
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\EloquentCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EloquentOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Free Shipping
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\Standard\TaxEngine

Livewire
Livewire: v3.2.1

Statamic
Addons: 5
Antlers: regex
Stache Watcher: Disabled
Static Caching: full
Version: 4.34.0 PRO

Statamic Addons
digiti/statamic-crow: 1.1.2
doublethreedigital/runway: 5.5.0
doublethreedigital/sc-digital-products: 5.1.1
doublethreedigital/simple-commerce: 5.6.2
statamic/seo-pro: 5.3.0

**Comment by duncanmcclean** [comment]
Have you added a variant product to the cart without a variant?

**Comment by wautersj** [comment]
No, the product-with-variants that was added has a variant

**Comment by duncanmcclean** [comment]
Does that product have a variant in the cart?

**Comment by wautersj** [comment]
Yes, if i check the cart, the product is there, with variant.

```
[
    {
        "id": "ba336572-2aa3-4c9f-b76f-305af498a6f5",
        "tax": {
            "rate": 21,
            "amount": 52,
            "price_includes_tax": true
        },
        "total": 247,
        "product": "3e65d692-a54f-44ac-9c97-5bc5ec10df36",
        "variant": {
            "product": "3e65d692-a54f-44ac-9c97-5bc5ec10df36",
            "variant": "100gr"
        },
        "metadata": [],
        "quantity": 1
    }
]
```

**Comment by duncanmcclean** [comment]
Okay! Are you able to share the content of the product's YAML file & the `line_items` array from the relevant order in the database.

I'll take a look at some point next week.

**Comment by wautersj** [comment]
The "Product with variations" yaml file;

```
title: 'Product with variations'
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              localizable: false
              validate:
                - required
          -
            handle: product_variants
            field:
              type: product_variants
              display: 'Product Variants'
              icon: product_variants
              localizable: false
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
              replicator_preview: true
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
          -
            handle: price
            field:
              save_zero_value: false
              type: money
              display: Price
              icon: generic
              localizable: false
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          -
            handle: tax_category
            field:
              type: tax_category
              display: 'Tax Category'
              max_items: 1
              mode: select
              localizable: true
      -
        fields:
          -
            handle: product_categories
            field:
              type: terms
              taxonomies:
                - product_categories
              display: 'Product categories'
              mode: select
              localizable: false
          -
            handle: product_subcategories
            field:
              type: terms
              taxonomies:
                - product_subcategories
              display: 'Product subcategories'
              mode: select
              localizable: false
      -
        fields:
          -
            handle: asset
            field:
              max_files: 1
              mode: list
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: Asset
              icon: assets
              localizable: false
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
  SEO:
    display: SEO
    sections:
      -
        fields:
          -
            handle: seo
            field:
              type: seo_pro
              listable: false
              display: SEO
              localizable: false
```

An example product created with the 'Product with variations' blueprint;

```
---
id: 523de287-cecd-4a5a-b981-e17c33d295f6
blueprint: product_with_variations
title: 'Agnus beef'
product_categories:
  - vlees
updated_by: e559da08-b31c-4d11-ab69-50b344e49df3
updated_at: 1699971102
product_variants:
  variants:
    -
      name: Gewicht
      values:
        - '100 gr'
        - '200 gr'
        - '300 gr'
        - '400 gr'
        - '500 gr'
        - '600 gr'
        - '700 gr'
        - '800 gr'
        - '900 gr'
        - '1 kg'
  options:
    -
      key: '100 gr'
      variant: '100 gr'
      price: 189
    -
      key: '200 gr'
      variant: '200 gr'
      price: 378
    -
      key: '300 gr'
      variant: '300 gr'
      price: 567
    -
      key: '400 gr'
      variant: '400 gr'
      price: 756
    -
      key: '500 gr'
      variant: '500 gr'
      price: 945
    -
      key: '600 gr'
      variant: '600 gr'
      price: 1134
    -
      key: '700 gr'
      variant: '700 gr'
      price: 1323
    -
      key: '800 gr'
      variant: '800 gr'
      price: 1512
    -
      key: '900 gr'
      variant: '900 gr'
      price: 1701
    -
      key: '1 kg'
      variant: '1 kg'
      price: 189
product_subcategories:
  - runds
tax_category: 9b70b5a2-73a8-4b5e-8f48-0f079f62a8cc
asset: dummies/screenshot-2023-11-14-at-15.11.13.png
---
```

The order lines straight from the DDB:

```
[
    {
        "id": "08396a20-050f-496e-b8d6-9d29029d2e33",
        "tax": {
            "rate": 6,
            "amount": 53,
            "price_includes_tax": true
        },
        "total": 892,
        "product": "523de287-cecd-4a5a-b981-e17c33d295f6",
        "variant": {
            "product": "523de287-cecd-4a5a-b981-e17c33d295f6",
            "variant": "500 gr"
        },
        "metadata": [],
        "quantity": 1
    }
]
```
